#!/usr/bin/env python
"""Drive the Kaggle freeze from this machine — upload code, push kernels, pull results back.

    python kaggle/push.py auth            # what to run to log in (one-time, interactive)
    python kaggle/push.py code            # upload/version the code dataset from ravaan-code.zip
    python kaggle/push.py push 00         # push the fetch+trial kernel — run this one FIRST
    python kaggle/push.py status 00       # poll it
    python kaggle/push.py logs 00         # its log, to read the trial verdict
    python kaggle/push.py pull 00         # download its output into reports/freeze/
    python kaggle/push.py push 01         # only after 00's verdict says FineWeb2 fits

    python kaggle/push.py data            # upload data/packed-pilot + §7's tokenizer
    python kaggle/push.py push 10         # G3's pilot: both arms, one seed, on a GPU

Kernel 00 is a decision gate. `neardedup.py` is not resumable — the shard reader checkpoints but
the MinHash index lives in memory — so a pass that overruns the ~12 h session cap produces
nothing. Do not push 01 or 02 until 00 says they fit.

Drives the `kaggle` CLI by subprocess rather than importing the package: the Python API surface
moved between 1.x and 2.x, the CLI did not. Metadata files are generated by the CLI's own `init`
subcommands so their filenames stay right across versions.

Auth in kaggle 2.2.3 is OAuth (`kaggle auth login`), not the ~/.kaggle/kaggle.json that older
docs describe. That login is interactive and browser-based, so it is yours to run; everything
after it is automatable.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import sysconfig
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
HERE = REPO / "kaggle"
CODE_ZIP = REPO / "ravaan-code.zip"
DATASET_SLUG = "ravaan-code"

# The slug is the only name here and the title is derived from it — see `title_for`. Kaggle
# slugifies the *title* and discards the slug half of `id`, so a pair that disagrees produces a
# kernel at an address this file cannot reach. Session 15's three all disagreed.
KERNELS = {
    "00": {
        "file": "freeze_00_fetch_and_trial.py",
        "slug": "ravaan-freeze-00-fetch-and-trial",
        "internet": True,
        "needs_corpus": False,
    },
    "01": {
        "file": "freeze_01_fineweb2.py",
        "slug": "ravaan-freeze-01-fineweb2",
        "internet": False,
        "needs_corpus": True,
    },
    "02": {
        "file": "freeze_02_roman.py",
        "slug": "ravaan-freeze-02-roman",
        "internet": False,
        "needs_corpus": True,
    },
    # The first kernel that trains anything, and the first that wants an accelerator. It mounts
    # the packed pilot corpus (`push.py data`) rather than kernel 00's raw-corpus output, so it
    # does not wait on the freeze — which is the whole reason G3 can be answered now.
    "10": {
        "file": "train_10_pilot.py",
        "slug": "ravaan-train-10-pilot",
        "internet": False,
        "needs_corpus": False,
        "gpu": True,
        "needs_packed": True,
    },
}

# `data/packed-pilot` plus §7's tokenizer, uploaded separately from the code so a code push does
# not re-upload a corpus and a corpus push does not invalidate the code dataset's version.
PILOT_SLUG = "ravaan-pilot"
PILOT_PATHS = ("data/packed-pilot", "data/tokenizer/ravaan-16k.model",
               "data/tokenizer/ravaan-16k.vocab", "data/tokenizer/ravaan-16k.json")

# Kaggle rejects a title under five characters; every slug here is far longer.
MIN_TITLE = 5


def title_for(slug: str) -> str:
    """The title Kaggle will slugify back into exactly `slug`.

    Kaggle derives a kernel's address from its title, not from the slug in `id` — measured, not
    assumed: session 15 pushed an `id` ending `-00-fetch-trial` under the title "... fetch and
    trial", and the live kernel came back `...-00-fetch-and-trial`. The slug was discarded.

    Deriving one from the other puts the same string in both fields, so it stops mattering which
    one Kaggle honours. The drift's cost was never the wrong title: `status`, `logs` and `pull`
    all queried an address that 403s, which is why an errored run sat unread for five weeks — and
    01 and 02 name 00 in `kernel_sources`, so they would have mounted no corpus and died the way
    00 did, after their trial had already been spent.
    """
    title = slug.replace("-", " ")
    if len(title) < MIN_TITLE:
        raise SystemExit(f"title {title!r} is under Kaggle's {MIN_TITLE}-character minimum")
    return title


def kaggle_exe() -> str:
    """Locate the CLI, which pip installs to a Scripts/bin directory that is often off PATH."""
    found = shutil.which("kaggle")
    if found:
        return found
    for key in ("scripts", "purelib"):
        base = sysconfig.get_path(key)
        if not base:
            continue
        for name in ("kaggle.exe", "kaggle"):
            candidate = Path(base).parent / "Scripts" / name
            if candidate.is_file():
                return str(candidate)
    # pip --user installs land outside sysconfig's prefix on Windows.
    for root in (Path.home() / "AppData/Roaming/Python", Path.home() / ".local"):
        hits = sorted(root.glob("**/Scripts/kaggle.exe")) + sorted(root.glob("bin/kaggle"))
        for candidate in hits:
            if candidate.is_file():
                return str(candidate)
    raise SystemExit("kaggle CLI not found — pip install kaggle")


def kaggle(*args: str, capture: bool = False, check: bool = True) -> str:
    argv = [kaggle_exe(), *args]
    if not capture:
        print(f"$ kaggle {' '.join(args)}", flush=True)
    result = subprocess.run(argv, capture_output=True, text=True, check=False)
    output = (result.stdout or "") + (result.stderr or "")
    if "Authentication required" in output:
        raise SystemExit(
            "not logged in. Run this once, in your shell (it opens a browser):\n"
            f"  {kaggle_exe()} auth login"
        )
    if check and result.returncode != 0:
        raise SystemExit(f"kaggle {' '.join(args)} failed:\n{output}")
    if not capture:
        print(output.rstrip(), flush=True)
    return output


def username() -> str:
    """Resolve the account slug that namespaces every dataset and kernel ref."""
    if os.environ.get("KAGGLE_USERNAME"):
        return os.environ["KAGGLE_USERNAME"]
    output = kaggle("config", "view", capture=True)
    for line in output.splitlines():
        if "username" in line.lower():
            parts = line.replace(":", " ").replace("=", " ").split()
            if parts:
                return parts[-1].strip()
    raise SystemExit(
        "could not read your kaggle username from `kaggle config view`.\n"
        "  set it explicitly:  kaggle config set -n username -v <your-slug>\n"
        "  or export KAGGLE_USERNAME=<your-slug>"
    )


def dataset_state(ref: str) -> str:
    """`ready`, or whatever Kaggle says instead. A 403 means the dataset does not exist."""
    return kaggle("datasets", "status", ref, capture=True, check=False).strip()


def wait_for_dataset(ref: str, *, timeout: float = 900.0) -> None:
    """Block until Kaggle has finished processing the dataset.

    A kernel that starts against a dataset still being processed mounts **nothing**, and the
    failure is a one-line `no code dataset found under /kaggle/input` a second and a half in.
    That is what happened on 2026-08-06: the dataset's files landed at 20:28:32 and the kernel
    started at 20:28:48. Sixteen seconds.

    So this is a precondition rather than a courtesy, and `cmd_push` refuses until it passes.
    """
    deadline = time.time() + timeout
    while True:
        state = dataset_state(ref)
        if state == "ready":
            print(f"dataset {ref}: ready", flush=True)
            return
        if "403" in state:
            raise SystemExit(
                f"dataset {ref} does not exist or is not yours — run:  python kaggle/push.py code"
            )
        if time.time() >= deadline:
            raise SystemExit(
                f"dataset {ref} still reports {state!r} after {timeout / 60:.0f} min — check "
                f"https://www.kaggle.com/datasets/{ref}"
            )
        print(f"dataset {ref}: {state or 'processing'} — waiting", flush=True)
        time.sleep(15)


def assert_ref_live(ref: str) -> None:
    """Confirm the kernel Kaggle created is at the address this file will ask for.

    The push succeeds either way; only this catches a slug the server rewrote.
    """
    output = kaggle("kernels", "status", ref, capture=True, check=False)
    if "denied" in output or "403" in output:
        listing = kaggle("kernels", "list", "--mine", capture=True, check=False)
        raise SystemExit(
            f"pushed, but {ref} is not reachable — Kaggle put it somewhere else.\n"
            f"your kernels:\n{listing}"
        )
    print(f"live at {ref}: {output.strip()}", flush=True)


def _metadata_file(folder: Path) -> Path:
    """The file the CLI's own `init` just wrote — name differs across versions."""
    candidates = sorted(folder.glob("*metadata*.json"))
    if not candidates:
        raise SystemExit(f"kaggle init wrote no metadata file into {folder}")
    return candidates[0]


def cmd_auth() -> int:
    exe = kaggle_exe()
    print(
        f"kaggle CLI: {exe}\n\n"
        "Log in once, interactively (opens a browser):\n"
        f"  {exe} auth login\n\n"
        "Then confirm it took:\n"
        f"  {exe} config view\n\n"
        "Phone verification is separate and also yours: kaggle.com -> Settings -> Phone\n"
        "Verification. It gates notebook internet access, which kernel 00's corpus fetch needs."
    )
    return 0


def cmd_code() -> int:
    if not CODE_ZIP.is_file():
        raise SystemExit(
            f"{CODE_ZIP} missing — rebuild it with:\n"
            "  git archive --format=zip -o ravaan-code.zip HEAD -- "
            "ravaan scripts configs pyproject.toml README.md"
        )
    ref = f"{username()}/{DATASET_SLUG}"

    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp)
        shutil.copy2(CODE_ZIP, staging / CODE_ZIP.name)

        kaggle("datasets", "init", "-p", str(staging))
        meta_path = _metadata_file(staging)
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        meta.update({"title": DATASET_SLUG, "id": ref, "licenses": [{"name": "Apache 2.0"}]})
        meta_path.write_text(
            json.dumps(meta, indent=2) + "\n", encoding="utf-8", newline="\n"
        )

        # Kaggle extracts uploaded .zip archives, so this mounts as the repo tree:
        # /kaggle/input/ravaan-code/{ravaan,scripts,...} — what the kernels glob for.
        #
        # Ask whether the dataset is ours, not whether a status call succeeded: `datasets status`
        # answers 403 (not "not found") for one that does not exist, so string-matching its
        # output sends a first upload down the `version` path, which then also 403s.
        listing = kaggle("datasets", "list", "--mine", capture=True, check=False)
        if DATASET_SLUG in listing:
            print(f"versioning existing dataset {ref}")
            kaggle(
                "datasets", "version", "-p", str(staging), "-m", "update from HEAD", "-r", "skip"
            )
        else:
            print(f"creating private dataset {ref}")
            kaggle("datasets", "create", "-p", str(staging), "-r", "skip")

    # Processing is asynchronous and a kernel pushed against an unprocessed dataset mounts
    # nothing, so wait here rather than let the next command lose a run to it.
    wait_for_dataset(ref)
    print(f"done: https://www.kaggle.com/datasets/{ref}")
    return 0


def cmd_data() -> int:
    """Upload `data/packed-pilot` and §7's tokenizer as the `ravaan-pilot` dataset.

    Separate from the code dataset because they change on different clocks: the code changes every
    session and the corpus changes when a pack runs. Versioning them together would re-upload
    ~15 MB of shards for a one-line fix, and — worse — would make "which corpus was this kernel
    run against" a question about a code version.
    """
    staged = [p for p in (REPO / q for q in PILOT_PATHS) if p.exists()]
    if not staged:
        raise SystemExit(
            "nothing to upload — run `python scripts/pack_pilot.py` first"
        )
    ref = f"{username()}/{PILOT_SLUG}"

    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp)
        for path in staged:
            target = staging / path.name
            if path.is_dir():
                shutil.copytree(path, target)
            else:
                shutil.copy2(path, target)

        size = sum(f.stat().st_size for f in staging.rglob("*") if f.is_file())
        print(f"staging {len(staged)} paths, {size / 1e6:.1f} MB")

        kaggle("datasets", "init", "-p", str(staging))
        meta_path = _metadata_file(staging)
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        meta.update({"title": PILOT_SLUG, "id": ref, "licenses": [{"name": "Apache 2.0"}]})
        meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8", newline="\n")

        listing = kaggle("datasets", "list", "--mine", capture=True, check=False)
        if PILOT_SLUG in listing:
            print(f"versioning existing dataset {ref}")
            kaggle("datasets", "version", "-p", str(staging), "-m", "repack", "-d")
        else:
            print(f"creating dataset {ref}")
            kaggle("datasets", "create", "-p", str(staging), "-d")

    wait_for_dataset(ref)
    print(f"done: https://www.kaggle.com/datasets/{ref}")
    return 0


def cmd_push(key: str) -> int:
    spec = KERNELS[key]
    user = username()
    ref = f"{user}/{spec['slug']}"

    # Two preconditions, each of which costs a whole session when it fails instead of refusing.
    wait_for_dataset(f"{user}/{DATASET_SLUG}")
    if spec.get("needs_packed"):
        wait_for_dataset(f"{user}/{PILOT_SLUG}")
    if spec["needs_corpus"]:
        gate = f"{user}/{KERNELS['00']['slug']}"
        state = kaggle("kernels", "status", gate, capture=True, check=False)
        if "COMPLETE" not in state:
            raise SystemExit(
                f"kernel 00 is not complete, and this kernel mounts its output as the corpus.\n"
                f"  {gate}: {state.strip()}\n"
                "Read its verdict first:  python kaggle/push.py logs 00"
            )

    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp)
        shutil.copy2(HERE / spec["file"], staging / spec["file"])

        kaggle("kernels", "init", "-p", str(staging))
        meta_path = _metadata_file(staging)
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        meta.update(
            {
                "id": ref,
                "title": title_for(spec["slug"]),
                "code_file": spec["file"],
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                # No GPU: this job never touches one, and a GPU session has a shorter cap.
                "enable_gpu": False,
                "enable_internet": spec["internet"],
                "dataset_sources": (
                    [f"{user}/{DATASET_SLUG}"]
                    + ([f"{user}/{PILOT_SLUG}"] if spec.get("needs_packed") else [])
                ),
                "kernel_sources": (
                    [f"{user}/{KERNELS['00']['slug']}"] if spec["needs_corpus"] else []
                ),
                "competition_sources": [],
            }
        )
        meta_path.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8", newline="\n")

        print(f"pushing {ref} (internet={spec['internet']}, corpus={spec['needs_corpus']})")
        kaggle("kernels", "push", "-p", str(staging))

    assert_ref_live(ref)
    print(f"\ndone: https://www.kaggle.com/code/{ref}")
    print(f"poll with:  python kaggle/push.py status {key}")
    return 0


def cmd_status(key: str) -> int:
    kaggle("kernels", "status", f"{username()}/{KERNELS[key]['slug']}")
    return 0


def cmd_logs(key: str) -> int:
    kaggle("kernels", "logs", f"{username()}/{KERNELS[key]['slug']}")
    return 0


def cmd_pull(key: str) -> int:
    ref = f"{username()}/{KERNELS[key]['slug']}"
    dest = REPO / "reports" / "freeze"
    dest.mkdir(parents=True, exist_ok=True)
    kaggle("kernels", "output", ref, "-p", str(dest))
    for item in sorted(dest.rglob("*")):
        if item.is_file():
            print(f"  {item.relative_to(REPO)}  {item.stat().st_size:,} bytes")
    print(
        "\nNow check the removal lists are accepted here — a header computed over a different\n"
        "read is refused by name rather than silently applied:\n"
        "  python scripts/split.py --source urdu-wikipedia --source fineweb2-urd_Arab \\\n"
        "      --source roman-urdu-parl --split train --limit 0 --measure-only \\\n"
        "      --exclude reports/freeze/removals_67_wikipedia.txt \\\n"
        "      --exclude reports/freeze/removals_67_fineweb2.txt \\\n"
        "      --exclude reports/freeze/removals_67_roman.txt \\\n"
        "      --plan-out reports/freeze/plan.json --heldout-out data/freeze/heldout.jsonl"
    )
    return 0


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 1
    command, rest = argv[0], argv[1:]

    if command == "auth":
        return cmd_auth()
    if command == "code":
        return cmd_code()
    if command == "data":
        return cmd_data()
    if command in {"push", "status", "pull", "logs"}:
        if not rest or rest[0] not in KERNELS:
            raise SystemExit(f"{command} needs a kernel: {', '.join(KERNELS)}")
        handlers = {"push": cmd_push, "status": cmd_status, "pull": cmd_pull, "logs": cmd_logs}
        return handlers[command](rest[0])

    raise SystemExit(
        f"unknown command {command!r} — one of: auth, code, data, push, status, logs, pull"
    )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
